import { Burger, Ingredient, Location } from '@/types'

export const burgers: Burger[] = [
  {
    id: 1,
    name: 'Classic Burger',
    price: 16,
    bun: 'Brioche',
    patty: 'Beef',
    spice: 'Mild',
    prepTime: '10–12 min',
    calories: 720,
    protein: 32,
    image: '/img-webp/burgerH.webp',
    description: 'The original Crazy Smash — perfectly seared patty, melted cheddar, crispy edges.',
  },
  {
    id: 2,
    name: 'Spicy Jalapeño',
    price: 18,
    bun: 'Brioche',
    patty: 'Beef',
    spice: 'Hot',
    prepTime: '12–14 min',
    calories: 810,
    protein: 34,
    image: '/img-webp/cheesyBurger.webp',
    description: 'Fiery jalapeños, pepper jack cheese, chipotle mayo on a toasted brioche.',
  },
  {
    id: 3,
    name: 'Bacon Cheese Burger',
    price: 21,
    bun: 'Brioche',
    patty: 'Beef',
    spice: 'Mild',
    prepTime: '12–15 min',
    calories: 900,
    protein: 37,
    image: '/img-webp/burgerwithhands.webp',
    description: 'Crispy smoked bacon, double cheddar, caramelized onions, smoky sauce.',
  },
  {
    id: 4,
    name: 'Veggie Delight',
    price: 15,
    bun: 'Sesame',
    patty: 'Veggie',
    spice: 'Mild',
    prepTime: '10–12 min',
    calories: 620,
    protein: 17,
    image: '/img-webp/burgerH.webp',
    description: 'House-made veggie patty, roasted peppers, avocado cream, micro herbs.',
  },
  {
    id: 5,
    name: 'BBQ Ranch',
    price: 19,
    bun: 'Brioche',
    patty: 'Beef',
    spice: 'Medium',
    prepTime: '12–14 min',
    calories: 870,
    protein: 36,
    image: '/img-webp/cheesyBurger.webp',
    description: 'Smoky BBQ glaze, house ranch, crispy onion strings, cheddar.',
  },
  {
    id: 6,
    name: 'Mushroom Swiss',
    price: 20,
    bun: 'Brioche',
    patty: 'Beef',
    spice: 'Mild',
    prepTime: '12–14 min',
    calories: 830,
    protein: 33,
    image: '/img-webp/burgerwithhands.webp',
    description: 'Sautéed wild mushrooms, Swiss cheese, truffle aioli, fresh thyme.',
  },
]

export const ingredients: Ingredient[] = [
  {
    id: 1,
    name: 'Freshly Greens',
    description: 'Crisp lettuce sourced daily from local organic farms.',
    image: '/img-webp/lettuce.webp',
    number: '01',
  },
  {
    id: 2,
    name: 'Juicy Tomatoes',
    description: 'Sun-ripened tomatoes that bring natural sweetness and balance.',
    image: '/img-webp/tomato.webp',
    number: '02',
  },
  {
    id: 3,
    name: 'Creamy Cheese',
    description: 'Rich, creamy cheese that melts into every bite.',
    image: '/img-webp/cheese-logo.webp',
    number: '03',
  },
  {
    id: 4,
    name: 'Perfect Patty',
    description: 'Grilled to perfection — juicy, smoky, unforgettable.',
    image: '/img-webp/meat.webp',
    number: '04',
  },
  {
    id: 5,
    name: 'Artisan Bun',
    description: 'Soft, toasted buns crafted to hold everything together.',
    image: '/img-webp/burgerH.webp',
    number: '05',
  },
]

export const locations: Location[] = [
  { city: 'Berlin', image: '/img-webp/berlin.webp' },
  { city: 'London', image: '/img-webp/london.webp' },
  { city: 'New York', image: '/img-webp/newyork.webp' },
  { city: 'Sydney', image: '/img-webp/sydney.webp' },
  { city: 'Tokyo', image: '/img-webp/tokyo.webp' },
]
