import { Burger, Ingredient } from '@/types'

export const burgers: Burger[] = [
  {
    id: 1,
    name: 'Classic Burger',
    price: 8,
    bun: 'Brioche',
    patty: 'Beef',
    spice: 'Mild',
    prepTime: '10–12 min',
    calories: 720,
    protein: 32,
    image: '/img/real/double-smash-burger-fries-drink.jpg',
    description: 'The original Crazy Smash — perfectly seared patty, melted cheddar, crispy edges.',
  },
  {
    id: 2,
    name: 'Spicy Jalapeño',
    price: 9,
    bun: 'Brioche',
    patty: 'Beef',
    spice: 'Hot',
    prepTime: '12–14 min',
    calories: 810,
    protein: 34,
    image: '/img/real/chicken-burger-fanta-fries.jpg',
    description: 'Fiery jalapeños, pepper jack cheese, chipotle mayo on a toasted brioche.',
  },
  {
    id: 3,
    name: 'Bacon Cheese Burger',
    price: 10,
    bun: 'Brioche',
    patty: 'Beef',
    spice: 'Mild',
    prepTime: '12–15 min',
    calories: 900,
    protein: 37,
    image: '/img/real/burger-closeup-hands.jpg',
    description: 'Crispy smoked bacon, double cheddar, caramelized onions, smoky sauce.',
  },
  {
    id: 4,
    name: 'Veggie Delight',
    price: 8,
    bun: 'Sesame',
    patty: 'Veggie',
    spice: 'Mild',
    prepTime: '10–12 min',
    calories: 620,
    protein: 17,
    image: '/img/real/burger-cola-tray.jpg',
    description: 'House-made veggie patty, roasted peppers, avocado cream, micro herbs.',
  },
  {
    id: 5,
    name: 'BBQ Ranch',
    price: 9,
    bun: 'Brioche',
    patty: 'Beef',
    spice: 'Medium',
    prepTime: '12–14 min',
    calories: 870,
    protein: 36,
    image: '/img/real/combo-tray-branded-wall.jpg',
    description: 'Smoky BBQ glaze, house ranch, crispy onion strings, cheddar.',
  },
  {
    id: 6,
    name: 'Mushroom Swiss',
    price: 9,
    bun: 'Brioche',
    patty: 'Beef',
    spice: 'Mild',
    prepTime: '12–14 min',
    calories: 830,
    protein: 33,
    image: '/img/real/double-burger-held-fries.jpg',
    description: 'Sautéed wild mushrooms, Swiss cheese, truffle aioli, fresh thyme.',
  },
]

export const ingredients: Ingredient[] = [
  {
    id: 1,
    name: 'Freshly Greens',
    description: 'Crisp lettuce, prepped fresh every day.',
    image: '/img-webp/lettuce.webp',
    number: '01',
  },
  {
    id: 2,
    name: 'Juicy Tomatoes',
    description: 'Sun-ripened tomatoes that bring natural sweetness and balance.',
    image: '/img-webp/tomato.webp',
    number: '02',
  },
  {
    id: 3,
    name: 'Creamy Cheese',
    description: 'Rich, creamy cheese that melts into every bite.',
    image: '/img-webp/cheese-logo.webp',
    number: '03',
  },
  {
    id: 4,
    name: 'Perfect Patty',
    description: 'Grilled to perfection — juicy, smoky, unforgettable.',
    image: '/img-webp/meat.webp',
    number: '04',
  },
  {
    id: 5,
    name: 'Artisan Bun',
    description: 'Soft, toasted buns crafted to hold everything together.',
    image: '/img/real/burger-cola-tray.jpg',
    number: '05',
  },
]

// Note: the old five-city 'locations' export was removed — it belonged to the
// original template's fictional international-shipping concept, which doesn't
// apply to this single-location Caserta shop. See TakeAway.tsx for the real content.
